source 'https://rubygems.org'

group :test do
  gem 'rspec', '~> 3.9'
  gem 'simplecov', '~> 0.18.5'
end

gem 'discord-notifier', '~> 1.0', '>= 1.0.3'
gem 'httparty', '~> 0.18.1'
gem 'rake', '~> 13.0', '>= 13.0.1'
gem 'slack-notifier', '~> 2.3', '>= 2.3.2'
